-- 日別ユーザ勤怠情報
CREATE TABLE DAILY_USER_WORK_DATA (
-- 日別勤怠データID
DAILY_USER_WORK_DATA_ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
-- ユーザID
USER_ID VARCHAR(16),
-- 企業コード
COMPANY_CODE VARCHAR(5),
-- 始業日時
WORK_START_DATE TIMESTAMP,
-- 終業日時
WORK_END_DATE TIMESTAMP,
-- 実労働時間
ACTUAL_WORK_TIME VARCHAR(5),
-- 登録日時
REG_DATE TIMESTAMP,
-- 更新日時
UPDATE_DATE TIMESTAMP
);
