-- ユーザ定時情報
CREATE TABLE USER_ONTIME_DATA (
-- ログインID
LOGIN_ID VARCHAR(16) NOT NULL PRIMARY KEY,
-- 始業時間
START_TIME VARCHAR(5),
-- 終業時間
END_TIME VARCHAR(5),
-- 登録日時
REG_DATE TIMESTAMP,
-- 更新日時
UPDATE_DATE TIMESTAMP
);
