SELECT
  *
FROM
  DAILY_USER_WORK_DATA
WHERE
  WORK_START_DATE BETWEEN /* workStartDate */'2019/01/01' AND /* workEndDate */'2019/01/31'
    AND
  USER_ID = /* userId */'test'
ORDER BY WORK_START_DATE